FROM ubuntu:22.04

RUN mkdir -p /app
WORKDIR /app

RUN apt-get update
RUN apt-get install -y clustalo ncbi-tools-bin
RUN apt-get install -y make rsync wget
RUN apt-get install -y git g++ libz-dev libbz2-dev bzip2 doxygen xsltproc docbook docbook-xsl docbook-xml autoconf automake autotools-dev liblog4cpp5-dev libperl-dev
RUN mkdir -p /deps

# install boost
WORKDIR /deps
RUN wget https://archives.boost.org/release/1.74.0/source/boost_1_74_0.tar.bz2
RUN tar xjf boost_1_74_0.tar.bz2
WORKDIR /deps/boost_1_74_0
RUN ./bootstrap.sh
RUN ./b2 install --prefix=/usr/local
RUN ldconfig

# Install libzeep
RUN git clone https://github.com/mhekkel/libzeep.git /deps/libzeep
WORKDIR /deps/libzeep
RUN git checkout tags/v4.0.0
RUN make -j
RUN make install
RUN ldconfig

WORKDIR /app
COPY . /app
RUN ./configure
RUN make -j
RUN make install

# The config file generated by the makefile is never correct.
# Previously the generated config file has been edited by hand to set the
# correct <base-url> address.
#
# The problem is that MRS_BASE_URL needs to be set to the hostname and port
# machine running the docker container for the web service (e.g.
# chelonium:18090) but to the externally visible hostname and port for the SOAP
# service (because this is set in the WSDL).
#
# We can workaround this by replacing the <base-url> value in the generated
# config.
RUN sed -i '30s/http\:\/\/chelonium\.cmbi\.umcn\.nl\:18090/https\:\/\/mrs.cmbi.umcn.nl/' /usr/local/etc/mrs/mrs-config.xml


EXPOSE 18090
